### PR TITLE
Additional shutdown_sync test

### PR DESCRIPTION
**Pull request by blackyblack**

### CODE REVIEW

**Review by Warchant — DISMISSED** [review]

**Comment by Warchant** [comment]
@blackyblack seems that this test fails

**Comment by blackyblack** [comment]
> @blackyblack seems that this test fails

Yes, it was a proof of the bug

**Comment by Warchant** [comment]
@blackyblack any idea how to fix?

**Comment by blackyblack** [comment]
> @blackyblack any idea how to fix?

Disable finalization, which is what we do for mainnet. Or review and fix finalization algorithm.

**Comment by blackyblack** [comment]
Another way to fix is to persist appliedBlockCount or remove appliedBlockCount check from the code. I don't think we should bother fixing it until proper finalization is done.

**Comment by Warchant** [comment]
Hm, not sure what closed this ...

**Comment by Warchant** [comment]
Merged in https://github.com/VeriBlock/vbk-ri-btc/pull/657

**Pull request closed without merging**
